=== GAMS-dev/miro/conf/GMSIO_config_schema.json
{  
  "$schema":"http://json-schema.org/draft-07/schema#",
  "title":"GAMS configuration file schema",
  "description":"Configuration file is automatically generated by GAMS and includes model specific data.",
  "type":"object",
  "additionalProperties":false,
  "properties":{  
    "pageTitle":{  
      "description":"Name of the page (displayed in browser tab)",
      "type":"string",
      "default":"GAMS WebUI",
      "required":false
    },
    "MIROSwitch":{  
      "description":"GAMS command line option to trigger the model to work under MIRO",
      "type":"string",
      "minLength":5,
      "required":true
    },
    "fileExchange":{  
      "description":"Method used to exchange files",
      "type":"string",
      "enum":[  
        "csv"
      ],
      "default":"csv",
      "required":false
    },
    "csvDelim":{  
      "description":"Column delimiter for csv files",
      "type":"string",
      "enum":[  
        ",",
        ";"
      ],
      "default":",",
      "required":false
    },
    "gamsInputFiles":{  
      "description":"Name of GAMS input data sheets. Identifiers are case insensitive.",
      "type":"object",
      "additionalProperties":{  
        "type":"object",
        "additionalProperties":false,
        "properties":{  
          "alias":{  
            "type":"string",
            "minLength":1
          },
          "symnames":{ 
            "description": "Symbol names in scalar tables",
            "type":"array",
            "minItems":1,
            "uniqueItems":true,
            "items":{
              "type":"string",
              "minLength":1
            }
          },
          "symtypes":{ 
            "description": "Symbol types in scalar tables",
            "type":"array",
            "minItems":1,
            "items":{
              "type":"string",
              "enum":["set","parameter"],
              "minLength":1
            }
          },
          "symtext":{ 
            "description": "Symbol aliases (exp. text) in scalar tables",
            "type":"array",
            "minItems":1,
            "items":{
              "type":"string",
              "minLength":1
            }
          },
          "headers":{  
            "description":"headers of the input sheets containing names of sets/parameters",
            "type":"object",
            "minProperties":1,
            "additionalProperties":{  
              "type":"object",
              "properties":{
                "alias":{  
                  "description":"Explanatory text of the header symbol",
                  "type":"string",
                  "minLength":1,
                  "required":true
                },
                "type":{  
                  "description":"GAMS input type",
                  "type":"string",
                  "enum":[  
                    "set",
                    "parameter",
                    "acronym",
                    "scalar"
                  ],
                  "required":true
                }
              }
            }
          }
        },
        "required":["headers"]
      }
    },
    "gamsOutputFiles":{  
      "description":"Name of GAMS input data sheets. Identifiers are case insensitive.",
      "type":"object",
      "minProperties":1,
      "additionalProperties":{  
        "type":"object",
        "additionalProperties":false,
        "properties":{  
          "alias":{  
            "type":"string",
            "minLength":1
          },
          "symnames":{ 
            "description": "Symbol names in scalar tables",
            "type":"array",
            "minItems":1,
            "uniqueItems":true,
            "items":{
              "type":"string",
              "minLength":1
            }
          },
          "symtypes":{ 
            "description": "Symbol types in scalar tables",
            "type":"array",
            "minItems":1,
            "items":{
              "type":"string",
              "enum":["set","parameter"],
              "minLength":1
            }
          },
          "symtext":{ 
            "description": "Symbol aliases (exp. text) in scalar tables",
            "type":"array",
            "minItems":1,
            "items":{
              "type":"string",
              "minLength":1
            }
          },
          "count":{  
            "description":"Only relevant for output scalars. Number of scalars in dataframe.",
            "type":"integer",
            "minimum":1,
            "required":false
          },
          "headers":{  
            "description":"headers of the output sheets containing names of sets/parameters",
            "type":"object",
            "minProperties":1,
            "additionalProperties":{  
              "type":"object",
              "properties":{  
                "type":{  
                  "description":"GAMS type",
                  "type":"string",
                  "enum":[  
                    "set",
                    "parameter",
                    "acronym",
                    "scalar"
                  ],
                  "required":true
                }
              }
            }
          }
        }
      }
    }
  }
}

=== GAMS-dev/miro/model/simple/conf/simple_io.json
{
    "pageTitle": "Simplified Energy Systems Model",
    "MIROSwitch": "MIRO=RUN",
    "fileExchange": "csv",
    "csvDelim": ",",
    "gamsInputFiles": {
        "planttypedata": {
            "alias": "Plant information",
            "headers": {
                "type": {
                    "type": "set",
                    "alias": "plant type"
                },
                "co2": {
                    "type": "parameter",
                    "alias": "CO2"
                },
                "cost": {
                    "type": "parameter",
                    "alias": "Cost"
                },
                "expansion cost": {
                    "type": "parameter",
                    "alias": "Expansion Cost"
                }
            }
        },
        "timeseries": {
            "alias": "base case time series [GWh]",
            "headers": {
                "ttx": {
                    "type": "set",
                    "alias": "Time Intervals"
                },
                "photovoltaic": {
                    "type": "parameter",
                    "alias": "photovoltaic"
                },
                "wind": {
                    "type": "parameter",
                    "alias": "wind"
                },
                "demand": {
                    "type": "parameter",
                    "alias": "Demand"
                }
            }
        }
    },
    "gamsOutputFiles": {
        "rep_emix": {
            "alias": "energy mix report",
            "headers": {
                "tt": {
                    "type": "set",
                    "alias": "time steps"
                },
                "rr": {
                    "type": "set",
                    "alias": "Regions"
                },
                "lng": {
                    "type": "parameter",
                    "alias": "lng"
                },
                "lat": {
                    "type": "parameter",
                    "alias": "lat"
                },
                "total": {
                    "type": "parameter",
                    "alias": "Total"
                },
                "renewable": {
                    "type": "parameter",
                    "alias": "Renewable"
                },
                "fossil": {
                    "type": "parameter",
                    "alias": "Fossil"
                }
            }
        },
        "rep_flow": {
            "alias": "flow report",
            "headers": {
                "tt": {
                    "type": "set",
                    "alias": "time steps"
                },
                "rr": {
                    "type": "set",
                    "alias": "Regions"
                },
                "rr_1": {
                    "type": "set",
                    "alias": "Regions"
                },
                "lng0": {
                    "type": "parameter",
                    "alias": "Lng0"
                },
                "lat0": {
                    "type": "parameter",
                    "alias": "Lat0"
                },
                "lng1": {
                    "type": "parameter",
                    "alias": "Lng1"
                },
                "lat1": {
                    "type": "parameter",
                    "alias": "Lat1"
                },
                "flow": {
                    "type": "parameter",
                    "alias": "Flow"
                }
            }
        },
        "scalars_out": {
            "alias": "Output Scalars",
            "symnames": [
                "obj_rep"
            ],
            "symtext": [
                "objective function value"
            ],
            "symtypes": [
                "parameter"
            ],
            "count": 1,
            "headers": {
                "scalar": {
                    "type": "set",
                    "alias": "Scalar Name"
                },
                "description": {
                    "type": "set",
                    "alias": "Scalar Description"
                },
                "value": {
                    "type": "set",
                    "alias": "Scalar Value"
                }
            }
        }
    }
}
