=== GAMS-dev/miro/conf/GMSIO_config_schema.json
{  
  "$schema":"http://json-schema.org/draft-07/schema#",
  "title":"GAMS configuration file schema",
  "description":"Configuration file is automatically generated by GAMS and includes model specific data.",
  "type":"object",
  "additionalProperties":false,
  "properties":{  
    "pageTitle":{  
      "description":"Name of the page (displayed in browser tab)",
      "type":"string",
      "default":"GAMS WebUI",
      "required":false
    },
    "MIROSwitch":{  
      "description":"GAMS command line option to trigger the model to work under MIRO",
      "type":"string",
      "minLength":5,
      "required":true
    },
    "fileExchange":{  
      "description":"Method used to exchange files",
      "type":"string",
      "enum":[  
        "csv"
      ],
      "default":"csv",
      "required":false
    },
    "csvDelim":{  
      "description":"Column delimiter for csv files",
      "type":"string",
      "enum":[  
        ",",
        ";"
      ],
      "default":",",
      "required":false
    },
    "gamsInputFiles":{  
      "description":"Name of GAMS input data sheets. Identifiers are case insensitive.",
      "type":"object",
      "additionalProperties":{  
        "type":"object",
        "additionalProperties":false,
        "properties":{  
          "alias":{  
            "type":"string",
            "minLength":1
          },
          "symnames":{ 
            "description": "Symbol names in scalar tables",
            "type":"array",
            "minItems":1,
            "uniqueItems":true,
            "items":{
              "type":"string",
              "minLength":1
            }
          },
          "symtypes":{ 
            "description": "Symbol types in scalar tables",
            "type":"array",
            "minItems":1,
            "items":{
              "type":"string",
              "enum":["set","parameter"],
              "minLength":1
            }
          },
          "symtext":{ 
            "description": "Symbol aliases (exp. text) in scalar tables",
            "type":"array",
            "minItems":1,
            "items":{
              "type":"string",
              "minLength":1
            }
          },
          "headers":{  
            "description":"headers of the input sheets containing names of sets/parameters",
            "type":"object",
            "minProperties":1,
            "additionalProperties":{  
              "type":"object",
              "properties":{
                "alias":{  
                  "description":"Explanatory text of the header symbol",
                  "type":"string",
                  "minLength":1,
                  "required":true
                },
                "type":{  
                  "description":"GAMS input type",
                  "type":"string",
                  "enum":[  
                    "set",
                    "parameter",
                    "acronym",
                    "scalar"
                  ],
                  "required":true
                }
              }
            }
          }
        },
        "required":["headers"]
      }
    },
    "gamsOutputFiles":{  
      "description":"Name of GAMS input data sheets. Identifiers are case insensitive.",
      "type":"object",
      "minProperties":1,
      "additionalProperties":{  
        "type":"object",
        "additionalProperties":false,
        "properties":{  
          "alias":{  
            "type":"string",
            "minLength":1
          },
          "symnames":{ 
            "description": "Symbol names in scalar tables",
            "type":"array",
            "minItems":1,
            "uniqueItems":true,
            "items":{
              "type":"string",
              "minLength":1
            }
          },
          "symtypes":{ 
            "description": "Symbol types in scalar tables",
            "type":"array",
            "minItems":1,
            "items":{
              "type":"string",
              "enum":["set","parameter"],
              "minLength":1
            }
          },
          "symtext":{ 
            "description": "Symbol aliases (exp. text) in scalar tables",
            "type":"array",
            "minItems":1,
            "items":{
              "type":"string",
              "minLength":1
            }
          },
          "count":{  
            "description":"Only relevant for output scalars. Number of scalars in dataframe.",
            "type":"integer",
            "minimum":1,
            "required":false
          },
          "headers":{  
            "description":"headers of the output sheets containing names of sets/parameters",
            "type":"object",
            "minProperties":1,
            "additionalProperties":{  
              "type":"object",
              "properties":{  
                "type":{  
                  "description":"GAMS type",
                  "type":"string",
                  "enum":[  
                    "set",
                    "parameter",
                    "acronym",
                    "scalar"
                  ],
                  "required":true
                }
              }
            }
          }
        }
      }
    }
  }
}

=== GAMS-dev/miro/model/gantt/conf/gantt_io.json
{
    "pageTitle": "A Transportation Problem (TRNSPORT,SEQ=1)",
    "MIROSwitch": "MIRO=RUN",
    "fileExchange": "csv",
    "csvDelim": ",",
    "gamsInputFiles": {},
    "gamsOutputFiles": {
        "gantt": {
            "alias": "asdasd",
            "headers": {
                "id": {
                    "type": "set",
                    "alias": "gannt_id"
                },
                "start": {
                    "type": "set",
                    "alias": "gannt_start"
                },
                "end": {
                    "type": "set",
                    "alias": "gannt_end"
                },
                "content": {
                    "type": "set",
                    "alias": "gannt_content"
                },
                "group": {
                    "type": "set",
                    "alias": "gantt_group"
                },
                "value": {
                    "type": "parameter",
                    "alias": "asdasd"
                }
            }
        }
    }
}

=== GAMS-dev/miro/model/transport/conf/transport_io.json
{
    "pageTitle": "A Transportation Problem with multiple version LP/MIP/MINLP",
    "MIROSwitch": "MIRO=RUN",
    "fileExchange": "csv",
    "csvDelim": ",",
    "gamsInputFiles": {
        "a": {
            "alias": "capacity of plant i in cases",
            "headers": {
                "i": {
                    "type": "set",
                    "alias": "canning plants"
                },
                "value": {
                    "type": "parameter",
                    "alias": "capacity of plant i in cases"
                }
            }
        },
        "b": {
            "alias": "demand at market j in cases",
            "headers": {
                "j": {
                    "type": "set",
                    "alias": "markets"
                },
                "value": {
                    "type": "parameter",
                    "alias": "demand at market j in cases"
                }
            }
        },
        "d": {
            "alias": "distance in thousands of miles \u20ac\u20ac",
            "headers": {
                "i": {
                    "type": "set",
                    "alias": "canning plants"
                },
                "j": {
                    "type": "set",
                    "alias": "markets"
                },
                "value": {
                    "type": "parameter",
                    "alias": "distance in thousands of miles \u20ac\u20ac"
                }
            }
        },
        "ilocdata": {
            "alias": "Plant location information",
            "headers": {
                "i": {
                    "type": "set",
                    "alias": "canning plants"
                },
                "lat": {
                    "type": "parameter",
                    "alias": "lat"
                },
                "lng": {
                    "type": "parameter",
                    "alias": "lng"
                }
            }
        },
        "jlocdata": {
            "alias": "Market location information",
            "headers": {
                "j": {
                    "type": "set",
                    "alias": "markets"
                },
                "lat": {
                    "type": "parameter",
                    "alias": "lat"
                },
                "lng": {
                    "type": "parameter",
                    "alias": "lng"
                }
            }
        },
        "scalars": {
            "alias": "Input Scalars",
            "symnames": [
                "f",
                "mins",
                "beta"
            ],
            "symtext": [
                "freight in dollars per case per thousand miles \u20ac\u20ac",
                "minimum shipment (MIP- and MINLP-only)",
                "beta (MINLP-only)"
            ],
            "symtypes": [
                "parameter",
                "parameter",
                "parameter"
            ],
            "headers": {
                "scalar": {
                    "type": "set",
                    "alias": "Scalar Name"
                },
                "description": {
                    "type": "set",
                    "alias": "Scalar Description"
                },
                "value": {
                    "type": "set",
                    "alias": "Scalar Value"
                }
            }
        }
    },
    "gamsOutputFiles": {
        "schedule": {
            "alias": "shipment quantities in cases",
            "headers": {
                "i": {
                    "type": "set",
                    "alias": "canning plants"
                },
                "j": {
                    "type": "set",
                    "alias": "markets"
                },
                "lngp": {
                    "type": "parameter",
                    "alias": "lngP"
                },
                "latp": {
                    "type": "parameter",
                    "alias": "latP"
                },
                "lngm": {
                    "type": "parameter",
                    "alias": "lngM"
                },
                "latm": {
                    "type": "parameter",
                    "alias": "latM"
                },
                "cap": {
                    "type": "parameter",
                    "alias": "cap"
                },
                "demand": {
                    "type": "parameter",
                    "alias": "demand"
                },
                "quantities": {
                    "type": "parameter",
                    "alias": "quantities"
                }
            }
        },
        "scalars_out": {
            "alias": "Output Scalars",
            "symnames": [
                "total_cost"
            ],
            "symtext": [
                "total transportation costs in thousands of dollars"
            ],
            "symtypes": [
                "parameter"
            ],
            "count": 1,
            "headers": {
                "scalar": {
                    "type": "set",
                    "alias": "Scalar Name"
                },
                "description": {
                    "type": "set",
                    "alias": "Scalar Description"
                },
                "value": {
                    "type": "set",
                    "alias": "Scalar Value"
                }
            }
        }
    }
}

=== GAMS-dev/miro/model/kport/conf/kport_io.json
{
    "pageTitle": "Product Portfolio Optimization",
    "MIROSwitch": "MIRO=RUN",
    "fileExchange": "csv",
    "csvDelim": ",",
    "gamsInputFiles": {
        "rdata": {
            "alias": "Reactor data",
            "headers": {
                "rr": {
                    "type": "set",
                    "alias": "Reactor"
                },
                "s": {
                    "type": "set",
                    "alias": "Scenario"
                },
                "rhdr": {
                    "type": "set",
                    "alias": "Reactor data headers"
                },
                "value": {
                    "type": "parameter",
                    "alias": "Reactor data"
                }
            }
        },
        "pdata": {
            "alias": "Product data",
            "headers": {
                "pp": {
                    "type": "set",
                    "alias": "Product"
                },
                "s": {
                    "type": "set",
                    "alias": "Scenario"
                },
                "demand": {
                    "type": "parameter",
                    "alias": "Demand"
                },
                "production time": {
                    "type": "parameter",
                    "alias": "Production Time"
                }
            }
        },
        "scalars": {
            "alias": "Input Scalars",
            "symnames": [
                "actscen",
                "whrs",
                "csti",
                "cstf",
                "esf"
            ],
            "symtext": [
                "Active scenario",
                "Length of considered period [hours]",
                "Depreciation cost per m^3 reactor and period [kEuro]",
                "Fixed cost per week and reactor [kEuro]",
                "Economies of scale factor"
            ],
            "symtypes": [
                "set",
                "parameter",
                "parameter",
                "parameter",
                "parameter"
            ],
            "headers": {
                "scalar": {
                    "type": "set",
                    "alias": "Scalar Name"
                },
                "description": {
                    "type": "set",
                    "alias": "Scalar Description"
                },
                "value": {
                    "type": "set",
                    "alias": "Scalar Value"
                }
            }
        }
    },
    "gamsOutputFiles": {
        "sppx": {
            "alias": "compute surplus production p",
            "headers": {
                "pp": {
                    "type": "set",
                    "alias": "Product"
                },
                "level": {
                    "type": "parameter",
                    "alias": "Level"
                },
                "marginal": {
                    "type": "parameter",
                    "alias": "Marginal"
                },
                "lower": {
                    "type": "parameter",
                    "alias": "Lower"
                },
                "upper": {
                    "type": "parameter",
                    "alias": "Upper"
                },
                "scale": {
                    "type": "parameter",
                    "alias": "Scale"
                }
            }
        },
        "cost": {
            "alias": "Cost report",
            "headers": {
                "chdr": {
                    "type": "set",
                    "alias": "Cost Header"
                },
                "value": {
                    "type": "parameter",
                    "alias": "Cost report"
                }
            }
        },
        "surplus": {
            "alias": "Demand/Surplus report",
            "headers": {
                "pp": {
                    "type": "set",
                    "alias": "Product"
                },
                "demand": {
                    "type": "parameter",
                    "alias": "Demand"
                },
                "surplus": {
                    "type": "parameter",
                    "alias": "Surplus"
                }
            }
        },
        "productiontime": {
            "alias": "Production time report",
            "headers": {
                "rr": {
                    "type": "set",
                    "alias": "Reactor"
                },
                "production time": {
                    "type": "parameter",
                    "alias": "Production Time"
                },
                "max. production time": {
                    "type": "parameter",
                    "alias": "max. Production Time"
                }
            }
        },
        "rpreport": {
            "alias": "Reactor/Product report",
            "headers": {
                "rr": {
                    "type": "set",
                    "alias": "Reactor"
                },
                "pp": {
                    "type": "set",
                    "alias": "Product"
                },
                "utilization rate": {
                    "type": "parameter",
                    "alias": "Utilization rate"
                },
                "number of batches": {
                    "type": "parameter",
                    "alias": "Number of batches"
                }
            }
        },
        "scalarsve_out": {
            "alias": "Output Variable/Equation Scalars",
            "headers": {
                "type": {
                    "type": "set",
                    "alias": "Type"
                },
                "scalar": {
                    "type": "set",
                    "alias": "Scalar Name"
                },
                "description": {
                    "type": "set",
                    "alias": "Scalar Description"
                },
                "level": {
                    "type": "parameter",
                    "alias": "Level"
                },
                "marginal": {
                    "type": "parameter",
                    "alias": "Marginal"
                },
                "lower": {
                    "type": "parameter",
                    "alias": "Lower"
                },
                "upper": {
                    "type": "parameter",
                    "alias": "Upper"
                },
                "scale": {
                    "type": "parameter",
                    "alias": "Scale"
                }
            }
        }
    }
}

=== GAMS-dev/miro/model/pickstock/conf/pickstock_io.json
{
    "pageTitle": "Stock Selection Optimization",
    "MIROSwitch": "MIRO=RUN",
    "fileExchange": "csv",
    "csvDelim": ",",
    "gamsInputFiles": {
        "price": {
            "alias": "Price",
            "headers": {
                "date": {
                    "type": "set",
                    "alias": "date"
                },
                "symbol": {
                    "type": "set",
                    "alias": "stock symbol"
                },
                "value": {
                    "type": "parameter",
                    "alias": "Price"
                }
            }
        },
        "scalars": {
            "alias": "Input Scalars",
            "symnames": [
                "maxstock",
                "trainingdays"
            ],
            "symtext": [
                "maximum number of stocks to select",
                "number of days for training"
            ],
            "symtypes": [
                "parameter",
                "parameter"
            ],
            "headers": {
                "scalar": {
                    "type": "set",
                    "alias": "Scalar Name"
                },
                "description": {
                    "type": "set",
                    "alias": "Scalar Description"
                },
                "value": {
                    "type": "set",
                    "alias": "Scalar Value"
                }
            }
        }
    },
    "gamsOutputFiles": {
        "deffit": {
            "alias": "fit to Dow Jones index",
            "headers": {
                "date": {
                    "type": "set",
                    "alias": "date"
                },
                "level": {
                    "type": "parameter",
                    "alias": "Level"
                },
                "marginal": {
                    "type": "parameter",
                    "alias": "Marginal"
                },
                "lower": {
                    "type": "parameter",
                    "alias": "Lower"
                },
                "upper": {
                    "type": "parameter",
                    "alias": "Upper"
                },
                "scale": {
                    "type": "parameter",
                    "alias": "Scale"
                }
            }
        },
        "partofportfolio": {
            "alias": "what part of the portfolio",
            "headers": {
                "symbol": {
                    "type": "set",
                    "alias": "stock symbol"
                },
                "value": {
                    "type": "parameter",
                    "alias": "what part of the portfolio"
                }
            }
        },
        "dowvsindex": {
            "alias": "dow jones vs. index fund",
            "headers": {
                "date": {
                    "type": "set",
                    "alias": "date"
                },
                "dj": {
                    "type": "parameter",
                    "alias": "dow jones"
                },
                "index fund": {
                    "type": "parameter",
                    "alias": "index fund"
                }
            }
        },
        "abserror": {
            "alias": "absolute error",
            "headers": {
                "date": {
                    "type": "set",
                    "alias": "date"
                },
                "absolute error train": {
                    "type": "parameter",
                    "alias": "absolute error train"
                },
                "absolute error test": {
                    "type": "parameter",
                    "alias": "absolute error test"
                }
            }
        },
        "pricemerge": {
            "alias": "Price (stocks & dow jones)",
            "headers": {
                "date": {
                    "type": "set",
                    "alias": "date"
                },
                "uni": {
                    "type": "set",
                    "alias": "Universal set"
                },
                "value": {
                    "type": "parameter",
                    "alias": "Price (stocks & dow jones)"
                }
            }
        },
        "scalars_out": {
            "alias": "Output Scalars",
            "symnames": [
                "kpi",
                "lastdaytraining"
            ],
            "symtext": [
                "key performance indicator - absoulte error in entire testing phase",
                "last date of training period"
            ],
            "symtypes": [
                "parameter",
                "set"
            ],
            "count": 2,
            "headers": {
                "scalar": {
                    "type": "set",
                    "alias": "Scalar Name"
                },
                "description": {
                    "type": "set",
                    "alias": "Scalar Description"
                },
                "value": {
                    "type": "set",
                    "alias": "Scalar Value"
                }
            }
        },
        "scalarsve_out": {
            "alias": "Output Variable/Equation Scalars",
            "headers": {
                "type": {
                    "type": "set",
                    "alias": "Type"
                },
                "scalar": {
                    "type": "set",
                    "alias": "Scalar Name"
                },
                "description": {
                    "type": "set",
                    "alias": "Scalar Description"
                },
                "level": {
                    "type": "parameter",
                    "alias": "Level"
                },
                "marginal": {
                    "type": "parameter",
                    "alias": "Marginal"
                },
                "lower": {
                    "type": "parameter",
                    "alias": "Lower"
                },
                "upper": {
                    "type": "parameter",
                    "alias": "Upper"
                },
                "scale": {
                    "type": "parameter",
                    "alias": "Scale"
                }
            }
        }
    }
}

=== GAMS-dev/miro/model/pickstock_live/conf/pickstock_live_io.json
{
    "pageTitle": "Stock Selection Optimization with live data from the web",
    "MIROSwitch": "MIRO=RUN",
    "fileExchange": "csv",
    "csvDelim": ",",
    "gamsInputFiles": {
        "scalars": {
            "alias": "Input Scalars",
            "symnames": [
                "maxstock",
                "trainingdays"
            ],
            "symtext": [
                "maximum number of stocks to select",
                "number of days for training"
            ],
            "symtypes": [
                "parameter",
                "parameter"
            ],
            "headers": {
                "scalar": {
                    "type": "set",
                    "alias": "Scalar Name"
                },
                "description": {
                    "type": "set",
                    "alias": "Scalar Description"
                },
                "value": {
                    "type": "set",
                    "alias": "Scalar Value"
                }
            }
        }
    },
    "gamsOutputFiles": {
        "price": {
            "alias": "stock price",
            "headers": {
                "date": {
                    "type": "set",
                    "alias": "date"
                },
                "symbol": {
                    "type": "set",
                    "alias": "stockSymbol"
                },
                "value": {
                    "type": "parameter",
                    "alias": "stock price"
                }
            }
        },
        "partofportfolio": {
            "alias": "what part of the portfolio",
            "headers": {
                "symbol": {
                    "type": "set",
                    "alias": "stockSymbol"
                },
                "value": {
                    "type": "parameter",
                    "alias": "what part of the portfolio"
                }
            }
        },
        "dowvsindex": {
            "alias": "dow jones vs. index fund",
            "headers": {
                "date": {
                    "type": "set",
                    "alias": "date"
                },
                "dj": {
                    "type": "parameter",
                    "alias": "dow jones"
                },
                "index fund": {
                    "type": "parameter",
                    "alias": "index fund"
                }
            }
        },
        "abserror": {
            "alias": "absolute error",
            "headers": {
                "date": {
                    "type": "set",
                    "alias": "date"
                },
                "absolute error train": {
                    "type": "parameter",
                    "alias": "absolute error train"
                },
                "absolute error test": {
                    "type": "parameter",
                    "alias": "absolute error test"
                }
            }
        },
        "scalars_out": {
            "alias": "Output Scalars",
            "symnames": [
                "lastdaytraining"
            ],
            "symtext": [
                "last date of training period [MIRO:hidden]"
            ],
            "symtypes": [
                "set"
            ],
            "count": 1,
            "headers": {
                "scalar": {
                    "type": "set",
                    "alias": "Scalar Name"
                },
                "description": {
                    "type": "set",
                    "alias": "Scalar Description"
                },
                "value": {
                    "type": "set",
                    "alias": "Scalar Value"
                }
            }
        },
        "scalarsve_out": {
            "alias": "Output Variable/Equation Scalars",
            "headers": {
                "type": {
                    "type": "set",
                    "alias": "Type"
                },
                "scalar": {
                    "type": "set",
                    "alias": "Scalar Name"
                },
                "description": {
                    "type": "set",
                    "alias": "Scalar Description"
                },
                "level": {
                    "type": "parameter",
                    "alias": "Level"
                },
                "marginal": {
                    "type": "parameter",
                    "alias": "Marginal"
                },
                "lower": {
                    "type": "parameter",
                    "alias": "Lower"
                },
                "upper": {
                    "type": "parameter",
                    "alias": "Upper"
                },
                "scale": {
                    "type": "parameter",
                    "alias": "Scale"
                }
            }
        }
    }
}
